package com.abhi.interfaces.runner;

import com.abhi.interfaces.internal.HDFCATM;
import com.abhi.interfaces.internal.ICICIBank;
import com.abhi.interfaces.internal.IndiaPost;
import com.abhi.interfaces.internal.ShellGasStation;
import com.abhi.interfaces.internal.DominosRestaurant;
import com.abhi.interfaces.rules.ATM;
import com.abhi.interfaces.rules.Bank;
import com.abhi.interfaces.rules.PostOffice;
import com.abhi.interfaces.rules.GasStation;
import com.abhi.interfaces.rules.Restaurant;

public class Runner2 {
    public static void main(String[] args) {
        ATM atm = new HDFCATM();
        atm.insertCard();
        atm.enterPin();
        atm.checkBalance();
        atm.withdrawCash();
        atm.depositCash();
        atm.transferMoney();
        atm.printReceipt();
        atm.ejectCard();
        atm.cancelTransaction();
        HDFCATM atm1 = new HDFCATM();
        atm1.insertCard();
        atm1.enterPin();
        atm1.checkBalance();
        atm1.withdrawCash();
        atm1.depositCash();
        atm1.transferMoney();
        atm1.printReceipt();
        atm1.ejectCard();
        atm1.cancelTransaction();
        System.out.println("===================================");

        Bank bank = new ICICIBank();
        bank.openAccount();
        bank.closeAccount();
        bank.depositMoney();
        bank.withdrawMoney();
        bank.checkAccountBalance();
        bank.applyLoan();
        bank.approveLoan();
        bank.transferFunds();
        bank.issueDebitCard();
        ICICIBank bank1 = new ICICIBank();
        bank1.openAccount();
        bank1.closeAccount();
        bank1.depositMoney();
        bank1.withdrawMoney();
        bank1.checkAccountBalance();
        bank1.applyLoan();
        bank1.approveLoan();
        bank1.transferFunds();
        bank1.issueDebitCard();
        System.out.println("===================================");

        PostOffice postOffice = new IndiaPost();
        postOffice.acceptParcel();
        postOffice.deliverParcel();
        postOffice.trackParcel();
        postOffice.buyStamp();
        postOffice.openSavingsAccount();
        postOffice.closeSavingsAccount();
        postOffice.applyForPostalServices();
        postOffice.issuePostalOrder();
        postOffice.checkPostageRates();
        IndiaPost postOffice1 = new IndiaPost();
        postOffice1.acceptParcel();
        postOffice1.deliverParcel();
        postOffice1.trackParcel();
        postOffice1.buyStamp();
        postOffice1.openSavingsAccount();
        postOffice1.closeSavingsAccount();
        postOffice1.applyForPostalServices();
        postOffice1.issuePostalOrder();
        postOffice1.checkPostageRates();
        System.out.println("===================================");

        GasStation gasStation = new ShellGasStation();
        gasStation.refuelCar();
        gasStation.checkOilLevel();
        gasStation.cleanWindshield();
        gasStation.checkTirePressure();
        gasStation.provideCarWash();
        gasStation.checkFuelPrices();
        gasStation.offerDiscount();
        gasStation.registerLoyaltyCard();
        gasStation.issueReceipt();
        ShellGasStation gasStation1 = new ShellGasStation();
        gasStation1.refuelCar();
        gasStation1.checkOilLevel();
        gasStation1.cleanWindshield();
        gasStation1.checkTirePressure();
        gasStation1.provideCarWash();
        gasStation1.checkFuelPrices();
        gasStation1.offerDiscount();
        gasStation1.registerLoyaltyCard();
        gasStation1.issueReceipt();
        System.out.println("===================================");

        Restaurant restaurant = new DominosRestaurant();
        restaurant.takeOrder();
        restaurant.serveFood();
        restaurant.processPayment();
        restaurant.prepareDish();
        restaurant.cleanTable();
        restaurant.refillDrinks();
        restaurant.greetCustomer();
        restaurant.giveBill();
        restaurant.reserveTable();
        DominosRestaurant restaurant1 = new DominosRestaurant();
        restaurant1.takeOrder();
        restaurant1.serveFood();
        restaurant1.processPayment();
        restaurant1.prepareDish();
        restaurant1.cleanTable();
        restaurant1.refillDrinks();
        restaurant1.greetCustomer();
        restaurant1.giveBill();
        restaurant1.reserveTable();
        System.out.println("===================================");
    }
}
