package com.abhi.override.runner;
import com.abhi.override.internal.*;


public class XmenRunner {
    public static void main(String[] args) {
        Xmen xmen=new Xmen();
        xmen.mutant();
        Xmen xmen1=new Wolverine();
        xmen1.mutant();
        Wolverine wolverine=new Wolverine();
        wolverine.mutant();
        wolverine.mutantPower();
        System.out.println("=====================");
        Telepath telepath = new Telepath();
        telepath.usePower();
        Telepath professorX = new CharlesXavier();
        professorX.usePower();
        CharlesXavier charles = new CharlesXavier();
        charles.usePower();
        charles.guideMutants();
        System.out.println("=====================");
        PhoenixHost phoenix = new PhoenixHost();
        phoenix.usePower();
        PhoenixHost jeanAsPhoenix = new JeanGrey();
        jeanAsPhoenix.usePower();
        JeanGrey jean = new JeanGrey();
        jean.usePower();
        jean.telekineticBlast();
        System.out.println("=====================");
        MagnetismMaster magnetism = new MagnetismMaster();
        magnetism.usePower();
        MagnetismMaster erikMagnet = new ErikLehnsherr();
        erikMagnet.usePower();
        ErikLehnsherr erik = new ErikLehnsherr();
        erik.usePower();
        erik.raiseMetalBridge();
        System.out.println("=====================");
        OpticBlaster blaster = new OpticBlaster();
        blaster.usePower();
        OpticBlaster scottBlast = new ScottSummers();
        scottBlast.usePower();
        ScottSummers scott = new ScottSummers();
        scott.usePower();
        scott.adjustVisor();
        System.out.println("=====================");
        WeatherController weather = new WeatherController();
        weather.usePower();
        WeatherController stormAsWeather = new StormMonroe();
        stormAsWeather.usePower();
        StormMonroe storm = new StormMonroe();
        storm.usePower();
        storm.callRain();
        System.out.println("=====================");
        BeastlyMutant beast = new BeastlyMutant();
        beast.usePower();
        BeastlyMutant hankAsBeast = new HankMcCoy();
        hankAsBeast.usePower();
        HankMcCoy hank = new HankMcCoy();
        hank.usePower();
        hank.quoteScientificTheory();
        System.out.println("=====================");
        Shapeshifter shapeshifter = new Shapeshifter();
        shapeshifter.usePower();
        Shapeshifter mystiqueDisguised = new Mystique();
        mystiqueDisguised.usePower();
        Mystique mystique = new Mystique();
        mystique.usePower();
        mystique.stealthAttack();
        System.out.println("=====================");
        Healer healer = new Healer();
        healer.usePower();
        Healer elixirAsHealer = new Elixir();
        elixirAsHealer.usePower();
        Elixir elixir = new Elixir();
        elixir.usePower();
        elixir.cureDisease();
        System.out.println("=====================");
        Phaser phaser = new Phaser();
        phaser.usePower();
        Phaser kittyAsPhaser = new KittyPryde();
        kittyAsPhaser.usePower();
        KittyPryde kitty = new KittyPryde();
        kitty.usePower();
        kitty.phaseOthers();
        System.out.println("=====================");
        TeleportingMutant teleMutant = new TeleportingMutant();
        teleMutant.usePower();
        TeleportingMutant nightAsTeleport = new Nightcrawler();
        nightAsTeleport.usePower();
        Nightcrawler nightcrawler = new Nightcrawler();
        nightcrawler.usePower();
        nightcrawler.shadowStrike();
        System.out.println("=====================");
        EnergyAbsorber absorber = new EnergyAbsorber();
        absorber.usePower();
        EnergyAbsorber rogueAbsorb = new Rogue();
        rogueAbsorb.usePower();
        Rogue rogue = new Rogue();
        rogue.usePower();
        rogue.mimicFlight();
        System.out.println("=====================");
        TimeManipulator manipulator = new TimeManipulator();
        manipulator.usePower();
        TimeManipulator cableTime = new Cable();
        cableTime.usePower();
        Cable cable = new Cable();
        cable.usePower();
        cable.activateTechWeapon();
        System.out.println("=====================");
        MetalSkinMutant metalMutant = new MetalSkinMutant();
        metalMutant.usePower();
        MetalSkinMutant colossusAsMetal = new Colossus();
        colossusAsMetal.usePower();
        Colossus colossus = new Colossus();
        colossus.usePower();
        colossus.punchGround();
        System.out.println("=====================");
        PsychicMutant psychic = new PsychicMutant();
        psychic.usePower();
        PsychicMutant emmaAsPsychic = new EmmaFrost();
        emmaAsPsychic.usePower();
        EmmaFrost emma = new EmmaFrost();
        emma.usePower();
        emma.diamondForm();
        System.out.println("=====================");
        EnergyProjector projector = new EnergyProjector();
        projector.usePower();
        EnergyProjector bishopAsProjector = new Bishop();
        bishopAsProjector.usePower();
        Bishop bishop = new Bishop();
        bishop.usePower();
        bishop.chargeRifle();
        System.out.println("=====================");
        Illusionist illusionist = new Illusionist();
        illusionist.usePower();
        Illusionist masterAsIllusion = new Mastermind();
        masterAsIllusion.usePower();
        Mastermind mastermind = new Mastermind();
        mastermind.usePower();
        mastermind.trapMind();
        System.out.println("=====================");
        WeatherMutant weather1 = new WeatherMutant();
        weather1.usePower();
        WeatherMutant forgeAsWeather = new Forge();
        forgeAsWeather.usePower();
        Forge forge = new Forge();
        forge.usePower();
        forge.inventWeapon();
        System.out.println("=====================");
        BeastMutant beastMutant = new BeastMutant();
        beastMutant.usePower();
        BeastMutant beastAsMutant = new Beast();
        beastAsMutant.usePower();
        Beast beast2 = new Beast();
        beast2.usePower();
        beast2.readInMidAir();
        System.out.println("=====================");
        TrackerMutant tracker = new TrackerMutant();
        tracker.usePower();
        TrackerMutant calibanAsTracker = new Caliban();
        calibanAsTracker.usePower();
        Caliban caliban = new Caliban();
        caliban.usePower();
        caliban.detectFear();
        System.out.println("=====================");
        PlasmaMutant plasma = new PlasmaMutant();
        plasma.usePower();
        PlasmaMutant havokAsPlasma = new Havok();
        havokAsPlasma.usePower();
        Havok havok = new Havok();
        havok.usePower();
        havok.energyBurst();
        System.out.println("=====================");
        ShadowMutant shadow = new ShadowMutant();
        shadow.usePower();
        ShadowMutant dominoAsShadow = new Domino();
        dominoAsShadow.usePower();
        Domino domino = new Domino();
        domino.usePower();
        domino.takeRisk();
        System.out.println("=====================");
        MagicUser magic = new MagicUser();
        magic.usePower();
        MagicUser magikAsMagic = new Magik();
        magikAsMagic.usePower();
        Magik magik = new Magik();
        magik.usePower();
        magik.summonSoulSword();
        System.out.println("=====================");
        SpeedMutant speed = new SpeedMutant();
        speed.usePower();
        SpeedMutant quicksilverAsSpeed = new Quicksilver();
        quicksilverAsSpeed.usePower();
        Quicksilver quicksilver = new Quicksilver();
        quicksilver.usePower();
        quicksilver.slowTimeEffect();
        System.out.println("=====================");
        SwordFighter fighter = new SwordFighter();
        fighter.usePower();
        SwordFighter samuraiAsFighter = new SilverSamurai();
        samuraiAsFighter.usePower();
        SilverSamurai samurai = new SilverSamurai();
        samurai.usePower();
        samurai.teleportWithArmor();
        System.out.println("=====================");
    }
}
