package com.abhi.override1.runner;
import com.abhi.override1.internal.GeniusKid;
import com.abhi.override1.internal.*;


public class Runner {
    public static void main(String[] args) {
        SuperSoldier soldier = new SuperSoldier();
        soldier.usePower();
        SuperSoldier capAsSoldier = new CaptainAmerica();
        capAsSoldier.usePower();
        CaptainAmerica cap = new CaptainAmerica();
        cap.usePower();
        cap.throwShield();
        System.out.println("=====================");
        ArmoredHero hero = new ArmoredHero();
        hero.usePower();
        ArmoredHero ironAsHero = new IronMan();
        ironAsHero.usePower();
        IronMan ironMan = new IronMan();
        ironMan.usePower();
        ironMan.launchMissiles();
        System.out.println("=====================");
        Asgardian god = new Asgardian();
        god.usePower();
        Asgardian thorAsGod = new Thor();
        thorAsGod.usePower();
        Thor thor = new Thor();
        thor.usePower();
        thor.callLightning();
        System.out.println("=====================");
        GeniusScientist bruce = new GeniusScientist();
        bruce.usePower();
        GeniusScientist hulkAsBruce = new Hulk();
        hulkAsBruce.usePower();
        Hulk hulk = new Hulk();
        hulk.usePower();
        hulk.smash();
        System.out.println("=====================");
        MysticMaster master = new MysticMaster();
        master.usePower();
        MysticMaster strangeAsMaster = new DoctorStrange();
        strangeAsMaster.usePower();
        DoctorStrange strange = new DoctorStrange();
        strange.usePower();
        strange.openPortal();
        System.out.println("=====================");
        StealthAgent agent = new StealthAgent();
        agent.usePower();
        StealthAgent widowAsAgent = new BlackWidow();
        widowAsAgent.usePower();
        BlackWidow widow = new BlackWidow();
        widow.usePower();
        widow.useSting();
        System.out.println("=====================");
        Sharpshooter shooter = new Sharpshooter();
        shooter.usePower();
        Sharpshooter hawkAsShooter = new Hawkeye();
        hawkAsShooter.usePower();
        Hawkeye hawk = new Hawkeye();
        hawk.usePower();
        hawk.fireArrow();
        System.out.println("=====================");
        WakandanHero hero1 = new WakandanHero();
        hero1.usePower();
        WakandanHero pantherAsHero = new BlackPanther();
        pantherAsHero.usePower();
        BlackPanther panther = new BlackPanther();
        panther.usePower();
        panther.activateSuit();
        System.out.println("=====================");
        SpiderHero hero2 = new SpiderHero();
        hero2.usePower();
        SpiderHero spideyAsHero = new SpiderMan();
        spideyAsHero.usePower();
        SpiderMan spidey = new SpiderMan();
        spidey.usePower();
        spidey.webShoot();
        System.out.println("=====================");
        ShrinkHero hero3 = new ShrinkHero();
        hero3.usePower();
        ShrinkHero antAsHero = new AntMan();
        antAsHero.usePower();
        AntMan antMan = new AntMan();
        antMan.usePower();
        antMan.rideAnt();
        System.out.println("=====================");
        ShieldHero hero4 = new ShieldHero();
        hero4.usePower();
        ShieldHero capAsHero = new CaptainAmerica1();
        capAsHero.usePower();
        CaptainAmerica1 cap1 = new CaptainAmerica1();
        cap.usePower();
        cap.throwShield();
        System.out.println("=====================");
        AndroidAvenger hero5 = new AndroidAvenger();
        hero5.usePower();
        AndroidAvenger visionAsHero = new Vision();
        visionAsHero.usePower();
        Vision vision = new Vision();
        vision.usePower();
        vision.fireBeam();
        System.out.println("=====================");
        WitchHero witch = new WitchHero();
        witch.usePower();
        WitchHero wandaAsWitch = new ScarletWitch();
        wandaAsWitch.usePower();
        ScarletWitch wanda = new ScarletWitch();
        wanda.usePower();
        wanda.createIllusion();
        System.out.println("=====================");
        InsectHero hero6 = new InsectHero();
        hero6.usePower();
        InsectHero waspAsHero = new Wasp();
        waspAsHero.usePower();
        Wasp wasp = new Wasp();
        wasp.usePower();
        wasp.stingAttack();
        System.out.println("=====================");
        TechPilot pilot = new TechPilot();
        pilot.usePower();
        TechPilot rhodeyAsPilot = new WarMachine();
        rhodeyAsPilot.usePower();
        WarMachine rhodey = new WarMachine();
        rhodey.usePower();
        rhodey.fireCannons();
        System.out.println("=====================");
        MagicHero hero7 = new MagicHero();
        hero7.usePower();
        MagicHero lokiAsHero = new Loki();
        lokiAsHero.usePower();
        Loki loki = new Loki();
        loki.usePower();
        loki.createClone();
        System.out.println("=====================");
        SpaceWarrior hero8 = new SpaceWarrior();
        hero8.usePower();
        SpaceWarrior starAsHero = new StarLord();
        starAsHero.usePower();
        StarLord star = new StarLord();
        star.usePower();
        star.playMusic();
        System.out.println("=====================");
        AlienFighter hero9 = new AlienFighter();
        hero9.usePower();
        AlienFighter draxAsHero = new Drax();
        draxAsHero.usePower();
        Drax drax = new Drax();
        drax.usePower();
        drax.takeRevenge();
        System.out.println("=====================");
        RocketHero hero10 = new RocketHero();
        hero10.usePower();
        RocketHero rocketAsHero = new RocketRaccoon();
        rocketAsHero.usePower();
        RocketRaccoon rocket = new RocketRaccoon();
        rocket.usePower();
        rocket.fixMachine();
        System.out.println("=====================");
        TreeBeing hero12 = new TreeBeing();
        hero12.usePower();
        TreeBeing grootAsHero = new Groot();
        grootAsHero.usePower();
        Groot groot = new Groot();
        groot.usePower();
        groot.sayName();
        System.out.println("=====================");
        WakandanWarrior hero13 = new WakandanWarrior();
        hero13.usePower();
        WakandanWarrior pantherAsHero1 = new BlackPanther1();
        pantherAsHero.usePower();
        BlackPanther1 panther1 = new BlackPanther1();
        panther.usePower();
        panther1.roar();
        System.out.println("=====================");
        SpyAgent hero14 = new SpyAgent();
        hero14.usePower();
        SpyAgent widowAsHero1 = new BlackWidow1();
        widowAsHero1.usePower();
        BlackWidow1 widow2 = new BlackWidow1();
        widow2.usePower();
        widow2.performTakedown();
        System.out.println("=====================");
        BowExpert hero16 = new BowExpert();
        hero16.usePower();
        BowExpert hawkeyeAsHero = new Hawkeye1();
        hawkeyeAsHero.usePower();
        Hawkeye1 hawkeye = new Hawkeye1();
        hawkeye.usePower();
        hawkeye.aimTarget();
        System.out.println("=====================");
        GeniusKid hero17 = new GeniusKid();
        hero17.usePower();
        GeniusKid shuriAsHero = new Shuri();
        shuriAsHero.usePower();
        Shuri shuri = new Shuri();
        shuri.usePower();
        shuri.hackSystem();
        System.out.println("=====================");
        ShieldMaster1 hero18 = new ShieldMaster1();
        hero18.usePower();
        ShieldMaster1 capAsHero2 = new CaptainAmerica3();
        capAsHero2.usePower();
        CaptainAmerica3 cap5 = new CaptainAmerica3();
        cap5.usePower();
        cap5.inspireTroops();
        System.out.println("=====================");
    }
}
